# ── Per-cluster mkcert TLS install ────────────────────────────────────────────
# Installs the wildcard mkcert cert (generated by ./bootstrap) as the default
# Traefik TLS certificate in each cluster, and trusts the mkcert CA inside
# each k3d node so Traefik can validate upstream uplinks.
#
# Cert + kubeconfig file paths come from the bootstrap workspace outputs.

locals {
  mkcert_dir              = data.terraform_remote_state.bootstrap.outputs.mkcert_dir
  mkcert_cert_pem         = "${local.mkcert_dir}/cert.pem"
  mkcert_key_pem          = "${local.mkcert_dir}/key.pem"
  kubeconfig_transit      = nonsensitive(local.transit.kubeconfig_path)
  kubeconfig_app_workload = nonsensitive(local.app_workload.kubeconfig_path)
  kubeconfig_ai_workload  = nonsensitive(local.ai_workload.kubeconfig_path)

  tlsstore_manifest = <<-MANIFEST
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: mkcert-tls
MANIFEST
}

resource "null_resource" "mkcert_transit" {
  triggers = { domain = var.domain }

  provisioner "local-exec" {
    command = <<-EOT
      docker exec k3d-transit-server-0 sh -c 'cat /etc/ssl/certs/mkcert-ca.pem >> /etc/ssl/certs/ca-certificates.crt'
      kubectl --kubeconfig=${local.kubeconfig_transit} -n traefik create secret tls mkcert-tls \
        --cert=${local.mkcert_cert_pem} \
        --key=${local.mkcert_key_pem} \
        --dry-run=client -o yaml | kubectl --kubeconfig=${local.kubeconfig_transit} apply -f -
      echo '${local.tlsstore_manifest}' | kubectl --kubeconfig=${local.kubeconfig_transit} apply -f -
    EOT
  }

  depends_on = [module.transit_traefik]
}

resource "null_resource" "mkcert_app_workload" {
  triggers = { domain = var.domain }

  provisioner "local-exec" {
    command = <<-EOT
      docker exec k3d-app-workload-server-0 sh -c 'cat /etc/ssl/certs/mkcert-ca.pem >> /etc/ssl/certs/ca-certificates.crt'
      kubectl --kubeconfig=${local.kubeconfig_app_workload} -n traefik create secret tls mkcert-tls \
        --cert=${local.mkcert_cert_pem} \
        --key=${local.mkcert_key_pem} \
        --dry-run=client -o yaml | kubectl --kubeconfig=${local.kubeconfig_app_workload} apply -f -
      echo '${local.tlsstore_manifest}' | kubectl --kubeconfig=${local.kubeconfig_app_workload} apply -f -
    EOT
  }

  depends_on = [module.app_workload_traefik]
}

resource "null_resource" "mkcert_ai_workload" {
  triggers = { domain = var.domain }

  provisioner "local-exec" {
    command = <<-EOT
      docker exec k3d-ai-workload-server-0 sh -c 'cat /etc/ssl/certs/mkcert-ca.pem >> /etc/ssl/certs/ca-certificates.crt'
      kubectl --kubeconfig=${local.kubeconfig_ai_workload} -n traefik create secret tls mkcert-tls \
        --cert=${local.mkcert_cert_pem} \
        --key=${local.mkcert_key_pem} \
        --dry-run=client -o yaml | kubectl --kubeconfig=${local.kubeconfig_ai_workload} apply -f -
      echo '${local.tlsstore_manifest}' | kubectl --kubeconfig=${local.kubeconfig_ai_workload} apply -f -
    EOT
  }

  depends_on = [module.ai_workload_traefik]
}
